# Data Analysis


1.   Pandas
2.   SQL

# Pandas
Pandas is a popular Python library that was made to help with data analysis. It’s free to use and comes with strong data structures and tools for working with structured data quickly. Pandas make it easier to work with and analyze data, no matter how big or small the files are.

What is Pandas?
You can think of Pandas as a set of versatile toolkits for working with data manipulation and analysis. Here is a list of its most important features:

Data loading and cleaning
Pandas can import data from many places, including CSV files, Excel spreadsheets, SQL databases, and more. It can also clean up imported data. It has tools to clean and preprocess data, such as tools for dealing with missing values, getting rid of duplicates, and fixing data that doesn’t match up.

Data manipulation
Pandas is great at many types of data manipulation, such as merging, filtering, sorting, grouping, and reshaping data. With these processes, users can change raw data into a format that can be analyzed and shown visually.

Data analysis
Pandas has built-in functions and methods for performing advanced data analysis tasks. These include assembling data sets, running statistical tests, and examining time series data.

Data visualisation
Pandas work well with well-known tools for data visualization, like Matplotlib and Seaborn, so users can make useful visualizations right from their Pandas DataFrames. This makes it easy to look into the data and share important insights.

Why use Pandas?
There are several reasons why Pandas is a good choice for data analysis tasks:

Efficiency
NumPy is a basic tool for numerical computing in Python that Pandas is built on top of. Pandas is good for both small—and large-scale data analysis tasks because it can quickly and efficiently work with large datasets and perform calculations.

Ease of Use
Pandas has an easy-to-understand syntax that lets people with different levels of programming knowledge use it. It’s easy to understand and work with because its DataFrame and Series data structures look like tabular data.

Versatility
Pandas can handle many types of data, such as number, categorical, text, and time series data. This flexibility lets users analyze different datasets with just one library, so they don’t need to use many different tools or libraries.

Integration
Pandas works well with NumPy, Matplotlib, scikit-learn, and other packages and tools common in the Python data science community. Because these libraries can talk to each other, users can combine the best parts of different libraries to perform difficult data analysis tasks well.

Pandas give data scientists, analysts, and researchers the tools they need to perform a wide range of data analysis tasks quickly and correctly. These features allow you to make the most of your datasets, clean your data, perform statistical analysis, or visualize your findings.

Installation

## 1. creating ,reading, writting

In [ ]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
pd.DataFrame({'Vegetables':[15,20],'Fruits':[25,30]})

   Vegetables  Fruits
0          15      25
1          20      30

In [ ]:
pd.DataFrame({'Vegetables':[15,20],'Fruits':[25,30]},index=["product A","product B"])

           Vegetables  Fruits
product A          15      25
product B          20      30

In [ ]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
pd.Series([1,2,3,4],index=["sales 1","sales 2","sales 3","sales 4"],name="product A")

sales 1    1
sales 2    2
sales 3    3
sales 4    4
Name: product A, dtype: int64

### read data

In [ ]:
df=pd.read_csv("/content/heart dataset.csv")
df.head(3)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1

In [ ]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
df.shape

(303, 14)

## 2. Indexing, Selecting and Assigning

In [ ]:
df.age                         # select age column
df["age"]                      # Also select age column
df["age"][0]                   # select first element of age column

0      63
1      37
2      41
3      56
4      57
       ..
298    57
299    45
300    68
301    57
302    57
Name: age, Length: 303, dtype: int64

In [ ]:
df["age"]

0      63
1      37
2      41
3      56
4      57
       ..
298    57
299    45
300    68
301    57
302    57
Name: age, Length: 303, dtype: int64

In [ ]:
df["age"][0]

63

### Indexing in pandas

Index-based selection¶
Pandas indexing works in one of two paradigms. The first is index-based selection: selecting data based on its numerical position in the data. iloc follows this paradigm.

To select the first row of data in a DataFrame, we may use the following:

In [ ]:
df.iloc[0]

age          63.0
sex           1.0
cp            3.0
trestbps    145.0
chol        233.0
fbs           1.0
restecg       0.0
thalach     150.0
exang         0.0
oldpeak       2.3
slope         0.0
ca            0.0
thal          1.0
target        1.0
Name: 0, dtype: float64

 To get a column with iloc, we can do the following:

In [ ]:
df.iloc[0]    # First row
df.iloc[:, 0]    # First column
df.iloc[:3, 0]    # First three rows of the first column
df.iloc[[0,1,2],0]   # first three elements of first column
df.iloc[-5:]   # last five elements of first column

In [ ]:
df.iloc[:,0]

0      63
1      37
2      41
3      56
4      57
       ..
298    57
299    45
300    68
301    57
302    57
Name: age, Length: 303, dtype: int64

On its own, the : operator, which also comes from native Python, means "everything". When combined with other selectors, however, it can be used to indicate a range of values. For example, to select the country column from just the first, second, and third row, we would do:

In [ ]:
df.iloc[:3,0]

0    63
1    37
2    41
Name: age, dtype: int64

Or, to select just the second and third entries, we would do:

In [ ]:
df.iloc[1:3,0]

1    37
2    41
Name: age, dtype: int64

In [ ]:
df.iloc[[0,1,2],0]

0    63
1    37
2    41
Name: age, dtype: int64

last five rows

In [ ]:
df.iloc[-5:]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

Label-based selection
The second paradigm for attribute selection is the one followed by the loc operator: label-based selection. In this paradigm, it's the data index value, not its position, which matters.

For example, to get the first entry in reviews, we would now do the following:

In [ ]:
df.loc[0,"age"]

63

In [ ]:
df.loc[:,["age","sex","cp"]]

     age  sex  cp
0     63    1   3
1     37    1   2
2     41    0   1
3     56    1   1
4     57    0   0
..   ...  ...  ..
298   57    0   0
299   45    1   3
300   68    1   0
301   57    1   0
302   57    0   1

[303 rows x 3 columns]

In [ ]:
df.loc[0, "age"]  # Value of 'age' in the first row
df.loc[:, ["age", "sex", "cp"]]  # Selected columns

## Conditional selection¶

In [ ]:
df.age==70

0      False
1      False
2      False
3      False
4      False
       ...
298    False
299    False
300    False
301    False
302    False
Name: age, Length: 303, dtype: bool

In [ ]:
df.loc[df.age==70]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
145,70,1,1,156,245,0,0,143,0,0.0,2,0,2,1
225,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
234,70,1,0,130,322,0,0,109,0,2.4,1,3,2,0
240,70,1,2,160,269,0,1,112,1,2.9,1,1,3,0

In [ ]:
df.loc[(df.age==70) &(df.target==1)]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
145,70,1,1,156,245,0,0,143,0,0.0,2,0,2,1

In [ ]:
df.loc[(df.age==70) | (df.target==1)]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,38,1,2,138,175,0,1,173,0,0.0,2,4,2,1
164,38,1,2,138,175,0,1,173,0,0.0,2,4,2,1
225,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
234,70,1,0,130,322,0,0,109,0,2.4,1,3,2,0
240,70,1,2,160,269,0,1,112,1,2.9,1,1,3,0

In [ ]:
df.loc[df.cp.isin([2,3])]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1
11,48,0,2,130,275,0,1,139,0,0.2,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,61,1,3,134,234,0,1,145,0,2.6,1,2,2,0
282,59,1,2,126,218,1,1,134,0,2.2,1,1,1,0
286,59,1,3,134,204,0,1,162,0,0.8,2,2,2,0
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0

In [ ]:
reviews.loc[reviews.price.notnull()]

In [ ]:
df.loc[df.age == 70]                               # age is 70
df.loc[(df.age == 70) & (df.target == 1)]          # age is 70 and target is 1
df.loc[df.cp.isin([2, 3])]                         # cp is 2 or 3
df.loc[(df.age==70) | (df.target==1)]              # age is 70 or target is 1

Assigning data

In [ ]:
df['critic'] = 'everyone'
df["target"]=1
df.head(2)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,critic
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1,everyone
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1,everyone

In [ ]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,critic
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1,everyone
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1,everyone
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1,everyone
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1,everyone
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1,everyone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0,everyone
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0,everyone
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0,everyone
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0,everyone
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0,everyone

## 3. Summary Functions and Map

In [ ]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [ ]:
df.age.describe()                # summary of specific column(age in this case)
df.age.mean()                    # mean of specific column (age)

count    303.000000
mean      54.366337
std        9.082101
min       29.000000
25%       47.500000
50%       55.000000
75%       61.000000
max       77.000000
Name: age, dtype: float64

In [ ]:
df.age.mean()

54.366336633663366

In [ ]:
df.head(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,critic
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1,everyone
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1,everyone
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1,everyone
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1,everyone
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1,everyone

In [ ]:
df.restecg.unique()         # how many unique values in a specific column

array([0, 1, 2])

In [ ]:
df.restecg.value_counts()

restecg
1    152
0    147
2      4
Name: count, dtype: int64

### Maps

In [ ]:
age_mean=df.age.mean()

In [ ]:
df.age-age_mean

0       8.633663
1     -17.366337
2     -13.366337
3       1.633663
4       2.633663
         ...
298     2.633663
299    -9.366337
300    13.633663
301     2.633663
302     2.633663
Name: age, Length: 303, dtype: float64

In [ ]:
age_mean = df.age.mean()
df['age_adjusted'] = df.age - age_mean

In [ ]:
df.head(2)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,critic,age_adjusted
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1,everyone,8.633663
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1,everyone,-17.366337

## 4. Grouping and Sorting

In [ ]:
df.groupby("sex").sex.count()

sex
0     96
1    207
Name: sex, dtype: int64

In [ ]:
df.groupby("sex").age.min()

sex
0    34
1    29
Name: age, dtype: int64

In [ ]:
df.groupby(['sex']).age.agg([len, min, max])

<ipython-input-4-805e46a65b60>:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby(['sex']).age.agg([len, min, max])
<ipython-input-4-805e46a65b60>:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby(['sex']).age.agg([len, min, max])

     len  min  max
sex
0     96   34   76
1    207   29   77

In [ ]:
df.groupby("sex").age.min()  # Minimum age by sex
df.groupby("sex").age.agg([len, min, max])  # Multiple aggregations

In [ ]:
# Sort by 'age' in ascending order
df_sorted = df.sort_values(by="age")
# in descending order
df_sorted_desc = df.sort_values(by="age", ascending=False)
print(df_sorted_desc)

In [ ]:
# Sort by 'sex', then by 'age'
df_multi_sorted = df.sort_values(by=["sex", "age"])

## 5. data types and missing values

In [ ]:
df.age.dtypes

dtype('int64')

In [ ]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [ ]:
df.fbs.astype("float64")

0      1.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
298    0.0
299    0.0
300    1.0
301    0.0
302    0.0
Name: fbs, Length: 303, dtype: float64

In [ ]:
df.index.dtype

dtype('int64')

In [ ]:
df.dtypes                      # display data types of all columns
df.age.dtypes                  # display data types of specific column(age)
df.fbs.astype("float64")       # change data type of specific column to specified data type

In [ ]:
df[pd.isnull(df.ca)]

Empty DataFrame
Columns: [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal, target]
Index: []

In [ ]:
pd.isnull().sum()          # checking number of missing values in all columns
df.age.isnull().sum()      # checking number of missing values in a specific column
df.fillna("mean")          # fill missing values with specified value

In [ ]:
df.age.fillna("unknown")

0      63
1      37
2      41
3      56
4      57
       ..
298    57
299    45
300    68
301    57
302    57
Name: age, Length: 303, dtype: int64

### replace

In [ ]:
df.age.replace(70, 80)

0      63
1      37
2      41
3      56
4      57
       ..
298    57
299    45
300    68
301    57
302    57
Name: age, Length: 303, dtype: int64

## 6. Renaming and Combining

In [ ]:
df.rename(columns={'critic': 'critical'})

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,critical
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1,everyone
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1,everyone
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1,everyone
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1,everyone
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1,everyone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0,everyone
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0,everyone
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0,everyone
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0,everyone
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0,everyone

In [ ]:
df.rename(index={0:"firstentry",1:"secondentry"})

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target,critic
firstentry,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1,everyone
secondentry,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1,everyone
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1,everyone
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1,everyone
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1,everyone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0,everyone
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0,everyone
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0,everyone
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0,everyone
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0,everyone

### Combining

In [ ]:
df1.append(df2)
pd.concat([df1, df2], axis=0)  # concatenation